### ISSUE TITLE
Server Crash NoClassDefFound

### ISSUE THREAD

**Issue by Shadows-of-Fire** [makeoo/Gadomancy#5]
Server crashes on startup. Crash report is as follows.
[01:18:08] [Server thread/ERROR] [FML/]: Caught exception from gadomancy
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
    at makeo.gadomancy.common.registration.RegisteredResearches.init(RegisteredResearches.java:40) ~[RegisteredResearches.class:?]
    at makeo.gadomancy.common.CommonProxy.postInitalize(CommonProxy.java:55) ~[CommonProxy.class:?]
    at makeo.gadomancy.common.Gadomancy.postInit(Gadomancy.java:76) ~[Gadomancy.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[Server.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[Server.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[Server.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[Server.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[Server.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[Server.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[Server.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[Server.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[Server.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[Server.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
    ... 34 more

Removing Gadomancy allows the server to run normally.
Forge 10.13.4.1492.
Entire log not included as it is >15000 lines long.

**Comment by makeo** [comment]
Mmmh looks weird. I'll try to reproduce it in a few hours.
Thanks!

**Comment by makeo** [comment]
Ok that was easy... I forgot to test  the mod in a server enviroment. Bug will be fixed today or tomorrow
Fix: https://github.com/makeoo/Gadomancy/commit/256369bad0b0bff4ff607b53c91942844948bcc2

**Comment by makeo** [comment]
Fixed with version 1.0.1
